version: "3"

services:
  backend:
    container_name: tg_api
    build: .
    restart: unless-stopped
    ports:
      - ${SERVER_PORTS}
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    container_name: tg_db
    image: "mongo:6-jammy"
    command: mongod --port ${DB_PORT}
    restart: always
    ports:
      - ${DB_LOCAL}:${DB_PORT}
    env_file:
      - .env
    volumes:
      - dbdata6:/data/db
          
volumes:
  dbdata6: