version: "3"

services:
  backend:
    container_name: tg_api
    build: .
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    container_name: tg_db
    image: "mongo:6-jammy"
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - dbdata6:/data/db
          
volumes:
  dbdata6: