version: "3"

services:
  mongodb:
    container_name: tg_db
    image: "mongo:6-jammy"
    restart: always
    ports:
      - "27018:27017"
    env_file:
      - .env
    volumes:
          - dbdata6:/data/db
          
volumes:
  dbdata6: